
jobs:
  - job: apply_databricks_scripts
    displayName: Apply Databricks scripts
    pool:
      vmImage: ubuntu-16.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.6"

      - bash: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install databricks-cli

          databricks --version
        displayName: Install Databricks CLI

      - bash: |
          cat >~/.databrickscfg <<EOL
          [DEFAULT]
          host = https://adb-8313415121770558.18.azuredatabricks.net
          token = $(DATABRICKS_TOKEN)
          EOL
        displayName: Configure Databricks CLI

      - task: ShellScript@2
        inputs:          
          scriptPath: $(Build.SourcesDirectory)/assets/setup.sh          
        displayName: Setup Databricks
